# Dados default exportados do SQLite

product_families = [{'created_at': '2025-08-18 13:03:32',
  'description': 'Sistemas de filtração da água',
  'display_order': 1,
  'id': 1,
  'is_active': 1,
  'name': 'Filtração'},
 {'created_at': '2025-08-21 09:09:48',
  'description': 'Produtos para recirculação de água e iluminação encastráveis',
  'display_order': 2,
  'id': 2,
  'is_active': 1,
  'name': 'Recirculação e Iluminação - Encastráveis Tanque Piscina'},
 {'created_at': '2025-08-22 15:58:43',
  'description': 'Produtos para tratamento e purificação da água da piscina',
  'display_order': 3,
  'id': 3,
  'is_active': 1,
  'name': 'Tratamento de Água'},
 {'created_at': '2025-08-26 08:55:58',
  'description': 'Produtos de revestimento para piscinas',
  'display_order': 4,
  'id': 4,
  'is_active': 1,
  'name': 'Revestimento'},
 {'created_at': '2025-08-26 09:15:35',
  'description': 'Produtos de revestimento para piscinas',
  'display_order': 4,
  'id': 5,
  'is_active': 1,
  'name': 'Revestimento'}]


product_categories = [{'description': None, 'display_order': 1, 'family_id': 1, 'id': 1, 'is_active': 1, 'name': 'Filtros de Areia'},
 {'description': None, 'display_order': 2, 'family_id': 1, 'id': 2, 'is_active': 1, 'name': 'Filtros de Cartucho'},
 {'description': None, 'display_order': 3, 'family_id': 1, 'id': 3, 'is_active': 1, 'name': 'Válvulas Seletoras'},
 {'description': None, 'display_order': 4, 'family_id': 1, 'id': 4, 'is_active': 1, 'name': 'Bomba de Filtração'},
 {'description': None, 'display_order': 5, 'family_id': 1, 'id': 5, 'is_active': 1, 'name': 'Vidros e Visores'},
 {'description': None, 'display_order': 6, 'family_id': 1, 'id': 6, 'is_active': 1, 'name': 'Quadros Elétricos'},
 {'description': None, 'display_order': 0, 'family_id': 1, 'id': 7, 'is_active': 1, 'name': 'Válvulas'},
 {'description': None, 'display_order': 0, 'family_id': 1, 'id': 8, 'is_active': 1, 'name': 'Bombas'},
 {'description': None, 'display_order': 1, 'family_id': 2, 'id': 9, 'is_active': 1, 'name': 'Skimmers'},
 {'description': None, 'display_order': 2, 'family_id': 2, 'id': 10, 'is_active': 1, 'name': 'Bocas de Impulsão'},
 {'description': None, 'display_order': 3, 'family_id': 2, 'id': 11, 'is_active': 1, 'name': 'Tomadas de Aspiração'},
 {'description': None, 'display_order': 4, 'family_id': 2, 'id': 12, 'is_active': 1, 'name': 'Acessórios Hidráulicos'},
 {'description': None, 'display_order': 5, 'family_id': 2, 'id': 13, 'is_active': 1, 'name': 'Reguladores de Nível'},
 {'description': None, 'display_order': 6, 'family_id': 2, 'id': 14, 'is_active': 1, 'name': 'Ralos de Fundo'},
 {'description': None, 'display_order': 7, 'family_id': 2, 'id': 15, 'is_active': 1, 'name': 'Iluminação LED'},
 {'description': None, 'display_order': 1, 'family_id': 3, 'id': 16, 'is_active': 1, 'name': 'Bombas de Dosagem'},
 {'description': None, 'display_order': 2, 'family_id': 3, 'id': 17, 'is_active': 1, 'name': 'Sistemas UV-C'},
 {'description': None, 'display_order': 3, 'family_id': 3, 'id': 18, 'is_active': 1, 'name': 'Sistemas de Eletrólise'},
 {'description': None, 'display_order': 4, 'family_id': 3, 'id': 19, 'is_active': 1, 'name': 'Químicos'},
 {'description': None, 'display_order': 5, 'family_id': 3, 'id': 20, 'is_active': 1, 'name': 'Proteção'},
 {'description': None, 'display_order': 1, 'family_id': 4, 'id': 21, 'is_active': 1, 'name': 'Telas'},
 {'description': None, 'display_order': 2, 'family_id': 4, 'id': 22, 'is_active': 1, 'name': 'Perfis'},
 {'description': None, 'display_order': 3, 'family_id': 4, 'id': 23, 'is_active': 1, 'name': 'Chapas'},
 {'description': None, 'display_order': 1, 'family_id': 4, 'id': 24, 'is_active': 1, 'name': 'Telas'},
 {'description': None, 'display_order': 2, 'family_id': 4, 'id': 25, 'is_active': 1, 'name': 'Perfis'}]


products = [{'base_price': 589,
  'brand': 'Astralpool',
  'category_id': 1,
  'code': 'FA-D450-8',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 1,
  'is_active': 1,
  'model': 'Aster D.450',
  'name': 'Filtro Aster Astralpool - D.450 8m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 625,
  'brand': 'Astralpool',
  'category_id': 1,
  'code': 'FA-D500-9',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 2,
  'is_active': 1,
  'model': 'Aster D.500',
  'name': 'Filtro Aster Astralpool - D.500 9m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 676,
  'brand': 'Astralpool',
  'category_id': 1,
  'code': 'FA-D600-14',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 3,
  'is_active': 1,
  'model': 'Aster D.600',
  'name': 'Filtro Aster Astralpool - D.600 14m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 987,
  'brand': 'Astralpool',
  'category_id': 1,
  'code': 'FA-D750-21',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 4,
  'is_active': 1,
  'model': 'Aster D.750',
  'name': 'Filtro Aster Astralpool - D.750 21m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 1259,
  'brand': 'Astralpool',
  'category_id': 1,
  'code': 'FA-D900-31',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 5,
  'is_active': 1,
  'model': 'Aster D.900',
  'name': 'Filtro Aster Astralpool - D.900 31m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 99,
  'brand': 'Generic',
  'category_id': 7,
  'code': 'VS-MANUAL',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 6,
  'is_active': 1,
  'model': 'Manual',
  'name': 'Válvula Selectora Manual',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 999,
  'brand': 'Aquark',
  'category_id': 7,
  'code': 'VS-IWASH',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 7,
  'is_active': 1,
  'model': 'iWash',
  'name': 'Válvula Selectora Automatica - iWash by aquark',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 890,
  'brand': 'Aquark',
  'category_id': 8,
  'code': 'BF-INV-1HP-16',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 8,
  'is_active': 1,
  'model': 'InverEco 1.0HP',
  'name': 'Bomba filtração Velocidade Variável InverEco 1.0HP(M) 16m3 By Aquark',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 990,
  'brand': 'Aquark',
  'category_id': 8,
  'code': 'BF-INV-1.5HP-20',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 9,
  'is_active': 1,
  'model': 'InverEco 1.5HP',
  'name': 'Bomba filtração Velocidade Variável InverEco 1.5HP(M) 20m3 By Aquark',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 1190,
  'brand': 'Aquark',
  'category_id': 8,
  'code': 'BF-INV-2HP-25',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 10,
  'is_active': 1,
  'model': 'InverEco 2.0HP',
  'name': 'Bomba filtração Velocidade Variável InverEco 2.0HP(M) 25m3 By Aquark',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 542,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-0.5HP-M-7.5',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 11,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 0.5HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 0,5HP(M) 7,5m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 540,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-0.75HP-M-11',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 12,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 0.75HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 0,75HP(M) 11m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 555,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-1HP-M-16',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 13,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 1.0HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 1,0HP(M) 16m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 668,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-1.5HP-M-21.5',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 14,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 1.5HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 1,5HP(M) 21,5m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 686,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-2HP-M-26',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 15,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 2.0HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 2,0HP(M) 26m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 727,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-3HP-M-35',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 16,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 3.0HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 3,0HP(M) 35m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 577,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-0.5HP-T-7.5',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 17,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 0.5HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 0,5HP(T) 7,5m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 612,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-0.75HP-T-11',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 18,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 0.75HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 0,75HP(T) 11m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 652,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-1HP-T-16',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 19,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 1.0HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 1,0HP(T) 16m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 711,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-1.5HP-T-21.5',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 20,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 1.5HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 1,5HP(T) 21,5m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 746,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-2HP-T-26',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 21,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 2.0HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 2,0HP(T) 26m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 768,
  'brand': 'Astralpool',
  'category_id': 8,
  'code': 'BF-VPS-3HP-T-35',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 22,
  'is_active': 1,
  'model': 'Vitoria Plus Silent 3.0HP',
  'name': 'Bomba de filtração Vitoria Plus Silent Astralpool - 3,0HP(T) 35m3/h',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 29.9,
  'brand': 'Generic',
  'category_id': 5,
  'code': 'VG-04-10-20KG',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 23,
  'is_active': 1,
  'model': '0.4-1.0mm',
  'name': 'Vidro granulado ionizado ativado - granulometria 0,4-1,0mm (Sacos de 20kg)',
  'unit': 'saco',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 29.9,
  'brand': 'Generic',
  'category_id': 5,
  'code': 'VG-15-30-20KG',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 24,
  'is_active': 1,
  'model': '1.5-3.0mm',
  'name': 'Vidro granulado ionizado ativado - granulometria 1,5-3,0mm (Sacos de 20kg)',
  'unit': 'saco',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 379,
  'brand': 'Astralpool',
  'category_id': 6,
  'code': 'QE-AST-B-230V16A',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 25,
  'is_active': 1,
  'model': 'Tipo B',
  'name': 'Quadro elect. Astralpool P/Bomba + Disj. c/Int. Dif. - Tipo B (2-4,6A) - 230V16A',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 379,
  'brand': 'Astralpool',
  'category_id': 6,
  'code': 'QE-AST-C-230V16A',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 26,
  'is_active': 1,
  'model': 'Tipo C',
  'name': 'Quadro elect. Astralpool P/Bomba + Disj. c/Int. Dif. - Tipo C (4-6A) - 230V16A',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 379,
  'brand': 'Astralpool',
  'category_id': 6,
  'code': 'QE-AST-D-230V16A',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 27,
  'is_active': 1,
  'model': 'Tipo D',
  'name': 'Quadro elect. Astralpool P/Bomba + Disj. c/Int. Dif. - Tipo D (6-10A) - 230V16A',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 990,
  'brand': 'Aquark',
  'category_id': 6,
  'code': 'QE-IGARDEN-50W',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 28,
  'is_active': 1,
  'model': 'iGarden 50W',
  'name': 'Quadro IGARDEN 50W By Aquark',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 1190,
  'brand': 'Aquark',
  'category_id': 6,
  'code': 'QE-IGARDEN-100W',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 29,
  'is_active': 1,
  'model': 'iGarden 100W',
  'name': 'Quadro IGARDEN 100W By Aquark',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 400.04,
  'brand': 'Hayward',
  'category_id': 6,
  'code': 'QE-HAY-MONO-50W-BT',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 30,
  'is_active': 1,
  'model': 'H-Power Mono 50W',
  'name': 'Quadro Hayward H-Power Mono + Trafo 50w + Bluetooth',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 451.08,
  'brand': 'Hayward',
  'category_id': 6,
  'code': 'QE-HAY-MONO-100W-BT',
  'cost_price': None,
  'created_at': '2025-08-18 13:14:02',
  'description': '',
  'id': 31,
  'is_active': 1,
  'model': 'H-Power Mono 100W',
  'name': 'Quadro Hayward H-Power Mono + Trafo 100w + Bluetooth',
  'unit': 'un',
  'updated_at': '2025-08-18 13:14:02'},
 {'base_price': 650,
  'brand': '',
  'category_id': 2,
  'code': 'FC-UNIVERSAL',
  'cost_price': None,
  'created_at': '2025-08-19 07:08:08',
  'description': 'Filtro de cartucho universal para piscinas interiores - adequado para qualquer capacidade',
  'id': 32,
  'is_active': 1,
  'model': '',
  'name': 'Filtro de Cartucho Universal',
  'unit': 'un',
  'updated_at': '2025-08-19 07:08:08'},
 {'base_price': 135,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-CL-BL-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Classis Boca Larga Branco Liner',
  'id': 33,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Classis Boca Larga Branco Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 104,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-STD-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Standard Branco Liner',
  'id': 34,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Standard Branco Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 210,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-LDA-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Linha de água Branco Liner',
  'id': 35,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Linha de água Branco Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 103,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-CL-BL-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Classis Boca Larga Branco Betão',
  'id': 36,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Classis Boca Larga Branco Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 73.2,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-STD-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Standard Branco Betão',
  'id': 37,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Standard Branco Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 165,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-LDA-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Linha de ãgua Branco Betão',
  'id': 38,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Linha de água Branco Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 1985,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-STD-INOX-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Standard em Aão inox AISI 316L Liner',
  'id': 39,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Standard em Aço inox AISI 316L Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 2147,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-STD-BL-INOX-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Standard Boca Larga em Aão inox AISI 316L Liner',
  'id': 40,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Standard Boca Larga em Aço inox AISI 316L Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 1453,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-STD-INOX-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Standard em Aão inox AISI 316L Betão',
  'id': 41,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Standard em Aço inox AISI 316L Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 1558,
  'brand': 'Astralpool',
  'category_id': 9,
  'code': 'SK-STD-BL-INOX-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Skimmer Standard Boca Larga em Aão inox AISI 316L Betão',
  'id': 42,
  'is_active': 1,
  'model': None,
  'name': 'Skimmer Standard Boca Larga em Aço inox AISI 316L Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 14.25,
  'brand': 'Astralpool',
  'category_id': 10,
  'code': 'BI-PAR-AST-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Boca de Impulsão de parede Astralpool Liner',
  'id': 43,
  'is_active': 1,
  'model': None,
  'name': 'Boca de Impulsão de parede Astralpool Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 196,
  'brand': 'Astralpool',
  'category_id': 10,
  'code': 'BI-PAR-INOX-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Boca de Impulsão de parede em Aão inox AISI 316L Liner',
  'id': 44,
  'is_active': 1,
  'model': None,
  'name': 'Boca de Impulsão de parede em Aço inox AISI 316L Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 8.55,
  'brand': 'Astralpool',
  'category_id': 10,
  'code': 'BI-PAR-AST-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Boca de Impulsão de parede Astralpool Betão',
  'id': 45,
  'is_active': 1,
  'model': None,
  'name': 'Boca de Impulsão de parede Astralpool Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 147,
  'brand': 'Astralpool',
  'category_id': 10,
  'code': 'BI-PAR-INOX-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Boca de Impulsão de parede em Aão inox AISI 316L Betão',
  'id': 46,
  'is_active': 1,
  'model': None,
  'name': 'Boca de Impulsão de parede em Aço inox AISI 316L Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 24.95,
  'brand': 'Astralpool',
  'category_id': 10,
  'code': 'BI-FUN-AST-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Boca de impulsão de fundo Astralpool Liner',
  'id': 47,
  'is_active': 1,
  'model': None,
  'name': 'Boca de impulsão de fundo Astralpool Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 196,
  'brand': 'Astralpool',
  'category_id': 10,
  'code': 'BI-FUN-INOX-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Boca de impulsão de fundo em aão inox AISI 316L Liner',
  'id': 48,
  'is_active': 1,
  'model': None,
  'name': 'Boca de impulsão de fundo em aço inox AISI 316L Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 12.8,
  'brand': 'Astralpool',
  'category_id': 10,
  'code': 'BI-FUN-AST-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Boca de impulsão de fundo Astralpool Betão',
  'id': 49,
  'is_active': 1,
  'model': None,
  'name': 'Boca de impulsão de fundo Astralpool Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 136,
  'brand': 'Astralpool',
  'category_id': 10,
  'code': 'BI-FUN-INOX-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Boca de impulsão de fundo em aão inox AISI 316L Betão',
  'id': 50,
  'is_active': 1,
  'model': None,
  'name': 'Boca de impulsão de fundo em aço inox AISI 316L Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 23.3,
  'brand': 'Astralpool',
  'category_id': 11,
  'code': 'TA-AST-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Tomada de Aspiração Astralpool Liner',
  'id': 51,
  'is_active': 1,
  'model': None,
  'name': 'Tomada de Aspiração Astralpool Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 8.6,
  'brand': 'Astralpool',
  'category_id': 11,
  'code': 'TA-AST-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Tomada de Aspiraãão Astralpool Betão',
  'id': 52,
  'is_active': 1,
  'model': None,
  'name': 'Tomada de Aspiração Astralpool Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 48.5,
  'brand': 'Astralpool',
  'category_id': 11,
  'code': 'TA-JOELHO-90',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Aspiraãão Branco com joelho 90ã',
  'id': 53,
  'is_active': 1,
  'model': None,
  'name': 'Aspiração Branco com joelho 90º',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 13.9,
  'brand': 'Astralpool',
  'category_id': 12,
  'code': 'PM-AST-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Passamuros Astralpool Liner',
  'id': 54,
  'is_active': 1,
  'model': None,
  'name': 'Passamuros Astralpool Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 13.9,
  'brand': 'Astralpool',
  'category_id': 12,
  'code': 'PM-AST-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Passamuros Astralpool Betão',
  'id': 55,
  'is_active': 1,
  'model': None,
  'name': 'Passamuros Astralpool Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 199,
  'brand': 'Astralpool',
  'category_id': 13,
  'code': 'RN-MEC-KRIPSOL',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Regulador de Nãvel mecãnico Kripsol',
  'id': 56,
  'is_active': 1,
  'model': None,
  'name': 'Regulador de Nível mecânico Kripsol',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 199,
  'brand': 'Astralpool',
  'category_id': 13,
  'code': 'RN-MEC-WISE',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Regulador de Nãvel mecãnico Wise',
  'id': 57,
  'is_active': 1,
  'model': None,
  'name': 'Regulador de Nível mecânico Wise',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 199,
  'brand': 'Astralpool',
  'category_id': 13,
  'code': 'RN-AST',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Regulador de Nãvel Astralpool',
  'id': 58,
  'is_active': 1,
  'model': None,
  'name': 'Regulador de Nível Astralpool',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 78,
  'brand': 'Astralpool',
  'category_id': 14,
  'code': 'RF-CIRC-290-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Ralo de fundo circular 290mm com insertos Astralpool Liner',
  'id': 59,
  'is_active': 1,
  'model': None,
  'name': 'Ralo de fundo circular 290mm com insertos Astralpool Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 46.35,
  'brand': 'Astralpool',
  'category_id': 14,
  'code': 'RF-KRIPSOL-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Ralo de fundo Kripsol Liner',
  'id': 60,
  'is_active': 1,
  'model': None,
  'name': 'Ralo de fundo Kripsol Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 797,
  'brand': 'Astralpool',
  'category_id': 14,
  'code': 'RF-INOX-LINER',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Ralo de fundo redondo em aão inox AISI 316L Liner',
  'id': 61,
  'is_active': 1,
  'model': None,
  'name': 'Ralo de fundo redondo em aço inox AISI 316L Liner',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 46,
  'brand': 'Astralpool',
  'category_id': 14,
  'code': 'RF-CIRC-270-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Ralo de fundo cicular 270mm Astralpool Betão',
  'id': 62,
  'is_active': 1,
  'model': None,
  'name': 'Ralo de fundo circular 270mm Astralpool Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 23.3,
  'brand': 'Astralpool',
  'category_id': 14,
  'code': 'RF-KRIPSOL-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Ralo de fundo Kripsol Betão',
  'id': 63,
  'is_active': 1,
  'model': None,
  'name': 'Ralo de fundo Kripsol Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 596,
  'brand': 'Astralpool',
  'category_id': 14,
  'code': 'RF-INOX-BETAO',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Ralo de fundo redondo em aão inox AISI 316L Betão',
  'id': 64,
  'is_active': 1,
  'model': None,
  'name': 'Ralo de fundo redondo em aço inox AISI 316L Betão',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 247,
  'brand': 'Astralpool',
  'category_id': 15,
  'code': 'LED-BRANCO-50',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Projector Led Luz Branca de 50mm',
  'id': 65,
  'is_active': 1,
  'model': None,
  'name': 'Projector Led Luz Branca de 50mm',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 343,
  'brand': 'Astralpool',
  'category_id': 15,
  'code': 'LED-BRANCO-100',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Projector Led Luz Branca de 100mm',
  'id': 66,
  'is_active': 1,
  'model': None,
  'name': 'Projector Led Luz Branca de 100mm',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 437,
  'brand': 'Astralpool',
  'category_id': 15,
  'code': 'LED-BRANCO-170',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Projector Led Luz Branca de 170mm',
  'id': 67,
  'is_active': 1,
  'model': None,
  'name': 'Projector Led Luz Branca de 170mm',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 266,
  'brand': 'Astralpool',
  'category_id': 15,
  'code': 'LED-ADAPTAVEL-50',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Projector Led Luz Branco Adaptãvel de 50mm',
  'id': 68,
  'is_active': 1,
  'model': None,
  'name': 'Projector Led Luz Branco Adaptável de 50mm',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 380,
  'brand': 'Astralpool',
  'category_id': 15,
  'code': 'LED-ADAPTAVEL-100',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Projector Led Luz Branco Adaptãvel de 100mm',
  'id': 69,
  'is_active': 1,
  'model': None,
  'name': 'Projector Led Luz Branco Adaptável de 100mm',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 480,
  'brand': 'Astralpool',
  'category_id': 15,
  'code': 'LED-ADAPTAVEL-170',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Projector Led Luz Branco Adaptãvel de 170mm',
  'id': 70,
  'is_active': 1,
  'model': None,
  'name': 'Projector Led Luz Branco Adaptável de 170mm',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 282,
  'brand': 'Astralpool',
  'category_id': 15,
  'code': 'LED-RGB-50',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Projector Led Luz RGB de 50mm',
  'id': 71,
  'is_active': 1,
  'model': None,
  'name': 'Projector Led Luz RGB de 50mm',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 423,
  'brand': 'Astralpool',
  'category_id': 15,
  'code': 'LED-RGB-100',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Projector Led Luz RGB de 100mm',
  'id': 72,
  'is_active': 1,
  'model': None,
  'name': 'Projector Led Luz RGB de 100mm',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 480,
  'brand': 'Astralpool',
  'category_id': 15,
  'code': 'LED-RGB-170',
  'cost_price': None,
  'created_at': '2025-08-21 09:09:48',
  'description': 'Produto de recirculaãão/iluminaãão - Projector Led Luz RGB de 170mm',
  'id': 73,
  'is_active': 1,
  'model': None,
  'name': 'Projector Led Luz RGB de 170mm',
  'unit': 'un',
  'updated_at': '2025-08-21 09:09:48'},
 {'base_price': 7.5,
  'brand': None,
  'category_id': 5,
  'code': 'AREIA-SILICA-06-12-25KG',
  'cost_price': None,
  'created_at': '2025-08-22 09:52:35',
  'description': '',
  'id': 74,
  'is_active': 1,
  'model': None,
  'name': 'Areia Sílica 0,6-1,2mm (25kg)',
  'unit': 'saco',
  'updated_at': '2025-08-22 09:52:35'},
 {'base_price': 7.5,
  'brand': None,
  'category_id': 5,
  'code': 'AREIA-SILICA-GROSSA-25KG',
  'cost_price': None,
  'created_at': '2025-08-22 09:52:35',
  'description': '',
  'id': 75,
  'is_active': 1,
  'model': None,
  'name': 'Areia Sílica Grossa (25kg)',
  'unit': 'saco',
  'updated_at': '2025-08-22 09:52:35'},
 {'base_price': 190,
  'brand': 'Generic',
  'category_id': 16,
  'code': 'BOMBA-PERIST-ECO-OXI',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Bomba Peristáltica Série Eco P/ Oxinégio Livre',
  'id': 76,
  'is_active': 1,
  'model': None,
  'name': 'Bomba Peristáltica Série Eco P/ Oxinégio Livre',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 890,
  'brand': 'Filtreau',
  'category_id': 17,
  'code': 'UV-TITAN-40W-18M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Sistema UV-C Titan 40w 18m3/h By Filtreau',
  'id': 77,
  'is_active': 1,
  'model': None,
  'name': 'Sistema UV-C Titan 40w 18m3/h By Filtreau',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 990,
  'brand': 'Filtreau',
  'category_id': 17,
  'code': 'UV-TITAN-80W-22M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Sistema UV-C Titan 80w 22m3/h By Filtreau',
  'id': 78,
  'is_active': 1,
  'model': None,
  'name': 'Sistema UV-C Titan 80w 22m3/h By Filtreau',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 1390,
  'brand': 'Filtreau',
  'category_id': 17,
  'code': 'UV-TITAN-120W-28M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Sistema UV-C Titan 120w 28m3/h By Filtreau',
  'id': 79,
  'is_active': 1,
  'model': None,
  'name': 'Sistema UV-C Titan 120w 28m3/h By Filtreau',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 590,
  'brand': 'Filtreau',
  'category_id': 17,
  'code': 'UV-SELECT-40W-18M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Sistema UV-C Select 40w 18m3/h By Filtreau',
  'id': 80,
  'is_active': 1,
  'model': None,
  'name': 'Sistema UV-C Select 40w 18m3/h By Filtreau',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 690,
  'brand': 'Filtreau',
  'category_id': 17,
  'code': 'UV-SELECT-80W-22M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Sistema UV-C Select 80w 22m3/h By Filtreau',
  'id': 81,
  'is_active': 1,
  'model': None,
  'name': 'Sistema UV-C Select 80w 22m3/h By Filtreau',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 990,
  'brand': 'Filtreau',
  'category_id': 17,
  'code': 'UV-SELECT-100W-28M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Sistema UV-C Select 100w 28m3/h By Filtreau',
  'id': 82,
  'is_active': 1,
  'model': None,
  'name': 'Sistema UV-C Select 100w 28m3/h By Filtreau',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 1750,
  'brand': 'Aquark',
  'category_id': 18,
  'code': 'MR-PURE-50M3-AQUARK',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Mr. Pure 50m3 By Aquark',
  'id': 83,
  'is_active': 1,
  'model': None,
  'name': 'Mr. Pure 50m3 By Aquark',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 1850,
  'brand': 'Aquark',
  'category_id': 18,
  'code': 'MR-PURE-90M3-AQUARK',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Mr. Pure 90m3 By Aquark',
  'id': 84,
  'is_active': 1,
  'model': None,
  'name': 'Mr. Pure 90m3 By Aquark',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 2250,
  'brand': 'Aquark',
  'category_id': 18,
  'code': 'MR-PURE-120M3-AQUARK',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Mr. Pure 120m3 By Aquark',
  'id': 85,
  'is_active': 1,
  'model': None,
  'name': 'Mr. Pure 120m3 By Aquark',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 845,
  'brand': 'Aquark',
  'category_id': 18,
  'code': 'INVERCLEAR-10GH-40M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Inverclear 10g/h By Aquark 40m3',
  'id': 86,
  'is_active': 1,
  'model': None,
  'name': 'Inverclear 10g/h By Aquark 40m3',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 890,
  'brand': 'Aquark',
  'category_id': 18,
  'code': 'INVERCLEAR-16GH-65M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Inverclear 16g/h By Aquark 65m3',
  'id': 87,
  'is_active': 1,
  'model': None,
  'name': 'Inverclear 16g/h By Aquark 65m3',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 945,
  'brand': 'Aquark',
  'category_id': 18,
  'code': 'INVERCLEAR-22GH-90M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Inverclear 22g/h By Aquark 90m3',
  'id': 88,
  'is_active': 1,
  'model': None,
  'name': 'Inverclear 22g/h By Aquark 90m3',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 990,
  'brand': 'Aquark',
  'category_id': 18,
  'code': 'INVERCLEAR-28GH-120M3',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Inverclear 28g/h By Aquark 120m3',
  'id': 89,
  'is_active': 1,
  'model': None,
  'name': 'Inverclear 28g/h By Aquark 120m3',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 399,
  'brand': 'Aquark',
  'category_id': 18,
  'code': 'KIT-UPGRADE-PH-INVERCLEAR',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Kit upgrade PH - Inverclear By Aquark',
  'id': 90,
  'is_active': 1,
  'model': None,
  'name': 'Kit upgrade PH - Inverclear By Aquark',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 9.9,
  'brand': 'Generic',
  'category_id': 19,
  'code': 'SAL-GRANULADO-REFINADO',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Sal Granulado Refinado',
  'id': 91,
  'is_active': 1,
  'model': None,
  'name': 'Sal Granulado Refinado',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 99,
  'brand': 'Generic',
  'category_id': 20,
  'code': 'PROTECAO-ANODICA',
  'cost_price': None,
  'created_at': '2025-08-22 15:58:43',
  'description': 'Produto de tratamento de água - Proteção Anódica',
  'id': 92,
  'is_active': 1,
  'model': None,
  'name': 'Proteção Anódica',
  'unit': 'un',
  'updated_at': '2025-08-22 15:58:43'},
 {'base_price': 345,
  'brand': 'Genérica',
  'category_id': 19,
  'code': 'DOSEADOR-AUTOMATICO-RX',
  'cost_price': None,
  'created_at': '2025-08-26 07:54:18',
  'description': 'Produto de tratamento de água - Doseador Automático RX',
  'id': 93,
  'is_active': 1,
  'model': None,
  'name': 'Doseador Automático RX',
  'unit': 'un',
  'updated_at': '2025-08-26 07:54:18'},
 {'base_price': 1799.8,
  'brand': 'CGT',
  'category_id': 21,
  'code': 'TELA-3D-UNICOLOR-CGT',
  'cost_price': None,
  'created_at': '2025-08-26 08:55:58',
  'description': 'Produto de revestimento - Revestimento Tela Armada 3D Unicolor CGT',
  'id': 94,
  'is_active': 1,
  'model': None,
  'name': 'Revestimento Tela Armada 3D Unicolor CGT',
  'unit': 'Vg',
  'updated_at': '2025-08-26 08:55:58'},
 {'base_price': 2428.8,
  'brand': 'CGT',
  'category_id': 21,
  'code': 'TELA-3D-CGT',
  'cost_price': None,
  'created_at': '2025-08-26 08:55:58',
  'description': 'Produto de revestimento - Revestimento Tela Armada 3D CGT',
  'id': 95,
  'is_active': 1,
  'model': None,
  'name': 'Revestimento Tela Armada 3D CGT',
  'unit': 'Vg',
  'updated_at': '2025-08-26 08:55:58'},
 {'base_price': 1760,
  'brand': 'CGT',
  'category_id': 21,
  'code': 'TELA-LISA-CGT',
  'cost_price': None,
  'created_at': '2025-08-26 08:55:58',
  'description': 'Produto de revestimento - Revestimento Tela Armada Lisa CGT',
  'id': 96,
  'is_active': 1,
  'model': None,
  'name': 'Revestimento Tela Armada Lisa CGT',
  'unit': 'Vg',
  'updated_at': '2025-08-26 08:55:58'},
 {'base_price': 5.25,
  'brand': 'Genérico',
  'category_id': 22,
  'code': 'PERFIL-HORIZONTAL-2ML',
  'cost_price': None,
  'created_at': '2025-08-26 08:55:58',
  'description': 'Produto de revestimento - Perfil Horizontal de Fixação (2ml)',
  'id': 97,
  'is_active': 1,
  'model': None,
  'name': 'Perfil Horizontal de Fixação (2ml)',
  'unit': 'un',
  'updated_at': '2025-08-26 08:55:58'},
 {'base_price': 6.3,
  'brand': 'Genérico',
  'category_id': 22,
  'code': 'PERFIL-VERTICAL-2ML',
  'cost_price': None,
  'created_at': '2025-08-26 08:55:58',
  'description': 'Produto de revestimento - Perfil Vertical para Renovação (2ml)',
  'id': 98,
  'is_active': 1,
  'model': None,
  'name': 'Perfil Vertical para Renovação (2ml)',
  'unit': 'un',
  'updated_at': '2025-08-26 08:55:58'},
 {'base_price': 7.5,
  'brand': 'Genérico',
  'category_id': 23,
  'code': 'CHAPA-COLAMINADA',
  'cost_price': None,
  'created_at': '2025-08-26 08:55:58',
  'description': 'Produto de revestimento - Chapa Colaminada',
  'id': 99,
  'is_active': 1,
  'model': None,
  'name': 'Chapa Colaminada',
  'unit': 'un',
  'updated_at': '2025-08-26 08:55:58'}]


attribute_types = [{'data_type': 'numeric',
  'description': 'Capacidade de filtração em metros cúbicos por hora',
  'id': 1,
  'name': 'Capacidade',
  'unit': 'm3/h'},
 {'data_type': 'text', 'description': 'Voltagem de operação', 'id': 2, 'name': 'Voltagem', 'unit': 'V'},
 {'data_type': 'numeric', 'description': 'Potência do motor', 'id': 3, 'name': 'Potência', 'unit': 'HP'},
 {'data_type': 'numeric', 'description': 'Diâmetro do equipamento', 'id': 4, 'name': 'Diâmetro', 'unit': 'mm'},
 {'data_type': 'text', 'description': 'Material de construção', 'id': 5, 'name': 'Material', 'unit': ''},
 {'data_type': 'select', 'description': 'Tipo de meio filtrante', 'id': 6, 'name': 'Tipo de Filtro', 'unit': ''},
 {'data_type': 'select', 'description': 'Local de instalação recomendado', 'id': 7, 'name': 'Localização', 'unit': ''},
 {'data_type': 'boolean', 'description': 'Suporte à automação', 'id': 8, 'name': 'Automação', 'unit': ''},
 {'data_type': 'select', 'description': 'Tipo de alimentação elétrica', 'id': 9, 'name': 'Fase', 'unit': ''},
 {'data_type': 'text', 'description': None, 'id': 10, 'name': 'Automacao', 'unit': None},
 {'data_type': 'numeric', 'description': None, 'id': 11, 'name': 'Potencia', 'unit': None},
 {'data_type': 'numeric', 'description': None, 'id': 12, 'name': 'Diametro', 'unit': None},
 {'data_type': 'text', 'description': None, 'id': 13, 'name': 'Tipo Filtro', 'unit': None},
 {'data_type': 'text', 'description': None, 'id': 14, 'name': 'Localizacao', 'unit': None},
 {'data_type': 'text', 'description': None, 'id': 15, 'name': 'Conectividade', 'unit': None},
 {'data_type': 'text', 'description': None, 'id': 16, 'name': 'Tipo Bomba', 'unit': None},
 {'data_type': 'numeric', 'description': None, 'id': 17, 'name': 'Peso', 'unit': None},
 {'data_type': 'text', 'description': None, 'id': 18, 'name': 'Granulometria', 'unit': None},
 {'data_type': 'text', 'description': None, 'id': 19, 'name': 'Amperagem', 'unit': None},
 {'data_type': 'text', 'description': None, 'id': 20, 'name': 'Tipo Protecao', 'unit': None},
 {'data_type': 'text', 'description': None, 'id': 21, 'name': 'Corrente Nominal', 'unit': None},
 {'data_type': 'text', 'description': None, 'id': 22, 'name': 'Transformador', 'unit': None},
 {'data_type': 'boolean', 'description': None, 'id': 23, 'name': 'Universal', 'unit': None},
 {'data_type': 'boolean', 'description': None, 'id': 24, 'name': 'Fácil Manutenção', 'unit': None},
 {'data_type': 'boolean', 'description': None, 'id': 25, 'name': 'Reutilizável', 'unit': None},
 {'data_type': 'text', 'description': 'Atributo Tipo', 'id': 26, 'name': 'Tipo', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Modelo', 'id': 27, 'name': 'Modelo', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Instalação', 'id': 28, 'name': 'Instalação', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Acessórios', 'id': 29, 'name': 'Acessórios', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Marca', 'id': 30, 'name': 'Marca', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Tecnologia', 'id': 31, 'name': 'Tecnologia', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Aplicação', 'id': 32, 'name': 'Aplicação', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Série', 'id': 33, 'name': 'Série', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Produção', 'id': 34, 'name': 'Produção', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Compatibilidade', 'id': 35, 'name': 'Compatibilidade', 'unit': ''},
 {'data_type': 'text', 'description': 'Atributo Qualidade', 'id': 36, 'name': 'Qualidade', 'unit': ''}]


product_attributes = [{'attribute_type_id': 1, 'id': 1, 'product_id': 1, 'value_boolean': None, 'value_numeric': 8, 'value_text': None},
 {'attribute_type_id': 12, 'id': 2, 'product_id': 1, 'value_boolean': None, 'value_numeric': 450, 'value_text': None},
 {'attribute_type_id': 13,
  'id': 3,
  'product_id': 1,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'areia'},
 {'attribute_type_id': 14,
  'id': 4,
  'product_id': 1,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'exterior'},
 {'attribute_type_id': 1, 'id': 5, 'product_id': 2, 'value_boolean': None, 'value_numeric': 9, 'value_text': None},
 {'attribute_type_id': 12, 'id': 6, 'product_id': 2, 'value_boolean': None, 'value_numeric': 500, 'value_text': None},
 {'attribute_type_id': 13,
  'id': 7,
  'product_id': 2,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'areia'},
 {'attribute_type_id': 14,
  'id': 8,
  'product_id': 2,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'exterior'},
 {'attribute_type_id': 1, 'id': 9, 'product_id': 3, 'value_boolean': None, 'value_numeric': 14, 'value_text': None},
 {'attribute_type_id': 12, 'id': 10, 'product_id': 3, 'value_boolean': None, 'value_numeric': 600, 'value_text': None},
 {'attribute_type_id': 13,
  'id': 11,
  'product_id': 3,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'areia'},
 {'attribute_type_id': 14,
  'id': 12,
  'product_id': 3,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'exterior'},
 {'attribute_type_id': 1, 'id': 13, 'product_id': 4, 'value_boolean': None, 'value_numeric': 21, 'value_text': None},
 {'attribute_type_id': 12, 'id': 14, 'product_id': 4, 'value_boolean': None, 'value_numeric': 750, 'value_text': None},
 {'attribute_type_id': 13,
  'id': 15,
  'product_id': 4,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'areia'},
 {'attribute_type_id': 14,
  'id': 16,
  'product_id': 4,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'exterior'},
 {'attribute_type_id': 1, 'id': 17, 'product_id': 5, 'value_boolean': None, 'value_numeric': 31, 'value_text': None},
 {'attribute_type_id': 12, 'id': 18, 'product_id': 5, 'value_boolean': None, 'value_numeric': 900, 'value_text': None},
 {'attribute_type_id': 13,
  'id': 19,
  'product_id': 5,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'areia'},
 {'attribute_type_id': 14,
  'id': 20,
  'product_id': 5,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'exterior'},
 {'attribute_type_id': 10,
  'id': 21,
  'product_id': 6,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Nao'},
 {'attribute_type_id': 5,
  'id': 22,
  'product_id': 6,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Bronze'},
 {'attribute_type_id': 10,
  'id': 23,
  'product_id': 7,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Sim'},
 {'attribute_type_id': 5,
  'id': 24,
  'product_id': 7,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Bronze'},
 {'attribute_type_id': 15,
  'id': 25,
  'product_id': 7,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Smart'},
 {'attribute_type_id': 1, 'id': 26, 'product_id': 8, 'value_boolean': None, 'value_numeric': 16, 'value_text': None},
 {'attribute_type_id': 11, 'id': 27, 'product_id': 8, 'value_boolean': None, 'value_numeric': 1, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 28,
  'product_id': 8,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 16,
  'id': 29,
  'product_id': 8,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'velocidade_variavel'},
 {'attribute_type_id': 1, 'id': 30, 'product_id': 9, 'value_boolean': None, 'value_numeric': 20, 'value_text': None},
 {'attribute_type_id': 11, 'id': 31, 'product_id': 9, 'value_boolean': None, 'value_numeric': 1.5, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 32,
  'product_id': 9,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 16,
  'id': 33,
  'product_id': 9,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'velocidade_variavel'},
 {'attribute_type_id': 1, 'id': 34, 'product_id': 10, 'value_boolean': None, 'value_numeric': 25, 'value_text': None},
 {'attribute_type_id': 11, 'id': 35, 'product_id': 10, 'value_boolean': None, 'value_numeric': 2, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 36,
  'product_id': 10,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 16,
  'id': 37,
  'product_id': 10,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'velocidade_variavel'},
 {'attribute_type_id': 1, 'id': 38, 'product_id': 11, 'value_boolean': None, 'value_numeric': 7.5, 'value_text': None},
 {'attribute_type_id': 11, 'id': 39, 'product_id': 11, 'value_boolean': None, 'value_numeric': 0.5, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 40,
  'product_id': 11,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 16,
  'id': 41,
  'product_id': 11,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 42, 'product_id': 12, 'value_boolean': None, 'value_numeric': 11, 'value_text': None},
 {'attribute_type_id': 11,
  'id': 43,
  'product_id': 12,
  'value_boolean': None,
  'value_numeric': 0.75,
  'value_text': None},
 {'attribute_type_id': 9,
  'id': 44,
  'product_id': 12,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 16,
  'id': 45,
  'product_id': 12,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 46, 'product_id': 13, 'value_boolean': None, 'value_numeric': 16, 'value_text': None},
 {'attribute_type_id': 11, 'id': 47, 'product_id': 13, 'value_boolean': None, 'value_numeric': 1, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 48,
  'product_id': 13,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 16,
  'id': 49,
  'product_id': 13,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 50, 'product_id': 14, 'value_boolean': None, 'value_numeric': 21.5, 'value_text': None},
 {'attribute_type_id': 11, 'id': 51, 'product_id': 14, 'value_boolean': None, 'value_numeric': 1.5, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 52,
  'product_id': 14,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 16,
  'id': 53,
  'product_id': 14,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 54, 'product_id': 15, 'value_boolean': None, 'value_numeric': 26, 'value_text': None},
 {'attribute_type_id': 11, 'id': 55, 'product_id': 15, 'value_boolean': None, 'value_numeric': 2, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 56,
  'product_id': 15,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 16,
  'id': 57,
  'product_id': 15,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 58, 'product_id': 16, 'value_boolean': None, 'value_numeric': 35, 'value_text': None},
 {'attribute_type_id': 11, 'id': 59, 'product_id': 16, 'value_boolean': None, 'value_numeric': 3, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 60,
  'product_id': 16,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 16,
  'id': 61,
  'product_id': 16,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 62, 'product_id': 17, 'value_boolean': None, 'value_numeric': 7.5, 'value_text': None},
 {'attribute_type_id': 11, 'id': 63, 'product_id': 17, 'value_boolean': None, 'value_numeric': 0.5, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 64,
  'product_id': 17,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'trifasica'},
 {'attribute_type_id': 16,
  'id': 65,
  'product_id': 17,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 66, 'product_id': 18, 'value_boolean': None, 'value_numeric': 11, 'value_text': None},
 {'attribute_type_id': 11,
  'id': 67,
  'product_id': 18,
  'value_boolean': None,
  'value_numeric': 0.75,
  'value_text': None},
 {'attribute_type_id': 9,
  'id': 68,
  'product_id': 18,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'trifasica'},
 {'attribute_type_id': 16,
  'id': 69,
  'product_id': 18,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 70, 'product_id': 19, 'value_boolean': None, 'value_numeric': 16, 'value_text': None},
 {'attribute_type_id': 11, 'id': 71, 'product_id': 19, 'value_boolean': None, 'value_numeric': 1, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 72,
  'product_id': 19,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'trifasica'},
 {'attribute_type_id': 16,
  'id': 73,
  'product_id': 19,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 74, 'product_id': 20, 'value_boolean': None, 'value_numeric': 21.5, 'value_text': None},
 {'attribute_type_id': 11, 'id': 75, 'product_id': 20, 'value_boolean': None, 'value_numeric': 1.5, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 76,
  'product_id': 20,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'trifasica'},
 {'attribute_type_id': 16,
  'id': 77,
  'product_id': 20,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 78, 'product_id': 21, 'value_boolean': None, 'value_numeric': 26, 'value_text': None},
 {'attribute_type_id': 11, 'id': 79, 'product_id': 21, 'value_boolean': None, 'value_numeric': 2, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 80,
  'product_id': 21,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'trifasica'},
 {'attribute_type_id': 16,
  'id': 81,
  'product_id': 21,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 1, 'id': 82, 'product_id': 22, 'value_boolean': None, 'value_numeric': 35, 'value_text': None},
 {'attribute_type_id': 11, 'id': 83, 'product_id': 22, 'value_boolean': None, 'value_numeric': 3, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 84,
  'product_id': 22,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'trifasica'},
 {'attribute_type_id': 16,
  'id': 85,
  'product_id': 22,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'standard'},
 {'attribute_type_id': 17, 'id': 86, 'product_id': 23, 'value_boolean': None, 'value_numeric': 20, 'value_text': None},
 {'attribute_type_id': 18,
  'id': 87,
  'product_id': 23,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '0.4-1.0mm'},
 {'attribute_type_id': 5,
  'id': 88,
  'product_id': 23,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'vidro_ativado'},
 {'attribute_type_id': 17, 'id': 89, 'product_id': 24, 'value_boolean': None, 'value_numeric': 20, 'value_text': None},
 {'attribute_type_id': 18,
  'id': 90,
  'product_id': 24,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '1.5-3.0mm'},
 {'attribute_type_id': 5,
  'id': 91,
  'product_id': 24,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'vidro_ativado'},
 {'attribute_type_id': 2,
  'id': 92,
  'product_id': 25,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '230V'},
 {'attribute_type_id': 19,
  'id': 93,
  'product_id': 25,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '16A'},
 {'attribute_type_id': 20, 'id': 94, 'product_id': 25, 'value_boolean': None, 'value_numeric': None, 'value_text': 'B'},
 {'attribute_type_id': 21,
  'id': 95,
  'product_id': 25,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '2-4.6A'},
 {'attribute_type_id': 2,
  'id': 96,
  'product_id': 26,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '230V'},
 {'attribute_type_id': 19,
  'id': 97,
  'product_id': 26,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '16A'},
 {'attribute_type_id': 20, 'id': 98, 'product_id': 26, 'value_boolean': None, 'value_numeric': None, 'value_text': 'C'},
 {'attribute_type_id': 21,
  'id': 99,
  'product_id': 26,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '4-6A'},
 {'attribute_type_id': 2,
  'id': 100,
  'product_id': 27,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '230V'},
 {'attribute_type_id': 19,
  'id': 101,
  'product_id': 27,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '16A'},
 {'attribute_type_id': 20,
  'id': 102,
  'product_id': 27,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'D'},
 {'attribute_type_id': 21,
  'id': 103,
  'product_id': 27,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': '6-10A'},
 {'attribute_type_id': 11, 'id': 104, 'product_id': 28, 'value_boolean': None, 'value_numeric': 50, 'value_text': None},
 {'attribute_type_id': 10,
  'id': 105,
  'product_id': 28,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Sim'},
 {'attribute_type_id': 15,
  'id': 106,
  'product_id': 28,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Smart'},
 {'attribute_type_id': 11,
  'id': 107,
  'product_id': 29,
  'value_boolean': None,
  'value_numeric': 100,
  'value_text': None},
 {'attribute_type_id': 10,
  'id': 108,
  'product_id': 29,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Sim'},
 {'attribute_type_id': 15,
  'id': 109,
  'product_id': 29,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Smart'},
 {'attribute_type_id': 11, 'id': 110, 'product_id': 30, 'value_boolean': None, 'value_numeric': 50, 'value_text': None},
 {'attribute_type_id': 9,
  'id': 111,
  'product_id': 30,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 15,
  'id': 112,
  'product_id': 30,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Bluetooth'},
 {'attribute_type_id': 22,
  'id': 113,
  'product_id': 30,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Sim'},
 {'attribute_type_id': 11,
  'id': 114,
  'product_id': 31,
  'value_boolean': None,
  'value_numeric': 100,
  'value_text': None},
 {'attribute_type_id': 9,
  'id': 115,
  'product_id': 31,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'monofasica'},
 {'attribute_type_id': 15,
  'id': 116,
  'product_id': 31,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Bluetooth'},
 {'attribute_type_id': 22,
  'id': 117,
  'product_id': 31,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Sim'},
 {'attribute_type_id': 1, 'id': 118, 'product_id': 32, 'value_boolean': None, 'value_numeric': 999, 'value_text': None},
 {'attribute_type_id': 6,
  'id': 119,
  'product_id': 32,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'cartucho'},
 {'attribute_type_id': 7,
  'id': 120,
  'product_id': 32,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'interior'},
 {'attribute_type_id': 23, 'id': 121, 'product_id': 32, 'value_boolean': 1, 'value_numeric': None, 'value_text': None},
 {'attribute_type_id': 5,
  'id': 122,
  'product_id': 32,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'poliéster plissado'},
 {'attribute_type_id': 24, 'id': 123, 'product_id': 32, 'value_boolean': 1, 'value_numeric': None, 'value_text': None},
 {'attribute_type_id': 25, 'id': 124, 'product_id': 32, 'value_boolean': 1, 'value_numeric': None, 'value_text': None},
 {'attribute_type_id': 5,
  'id': 125,
  'product_id': 33,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 26, 'id': 126, 'product_id': 33, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 27,
  'id': 127,
  'product_id': 33,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Classic'},
 {'attribute_type_id': 5,
  'id': 128,
  'product_id': 34,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 26, 'id': 129, 'product_id': 34, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 27,
  'id': 130,
  'product_id': 34,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Standard'},
 {'attribute_type_id': 5,
  'id': 131,
  'product_id': 35,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 26, 'id': 132, 'product_id': 35, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 27,
  'id': 133,
  'product_id': 35,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Linha de Água'},
 {'attribute_type_id': 5,
  'id': 134,
  'product_id': 36,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 26, 'id': 135, 'product_id': 36, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 27,
  'id': 136,
  'product_id': 36,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Classic'},
 {'attribute_type_id': 5,
  'id': 137,
  'product_id': 37,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 26, 'id': 138, 'product_id': 37, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 27,
  'id': 139,
  'product_id': 37,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Standard'},
 {'attribute_type_id': 5,
  'id': 140,
  'product_id': 38,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 26, 'id': 141, 'product_id': 38, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 27,
  'id': 142,
  'product_id': 38,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Linha de Água'},
 {'attribute_type_id': 5,
  'id': 143,
  'product_id': 39,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 26, 'id': 144, 'product_id': 39, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 27,
  'id': 145,
  'product_id': 39,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Standard'},
 {'attribute_type_id': 5,
  'id': 146,
  'product_id': 40,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 26, 'id': 147, 'product_id': 40, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 27,
  'id': 148,
  'product_id': 40,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Standard Boca Larga'},
 {'attribute_type_id': 5,
  'id': 149,
  'product_id': 41,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 26, 'id': 150, 'product_id': 41, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 27,
  'id': 151,
  'product_id': 41,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Standard'},
 {'attribute_type_id': 5,
  'id': 152,
  'product_id': 42,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 26, 'id': 153, 'product_id': 42, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 27,
  'id': 154,
  'product_id': 42,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Standard Boca Larga'},
 {'attribute_type_id': 26, 'id': 155, 'product_id': 43, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Parede'},
 {'attribute_type_id': 5,
  'id': 156,
  'product_id': 43,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 28, 'id': 157, 'product_id': 43, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 26, 'id': 158, 'product_id': 44, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Parede'},
 {'attribute_type_id': 5,
  'id': 159,
  'product_id': 44,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 28, 'id': 160, 'product_id': 44, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 26, 'id': 161, 'product_id': 45, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Parede'},
 {'attribute_type_id': 5,
  'id': 162,
  'product_id': 45,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 28, 'id': 163, 'product_id': 45, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 26, 'id': 164, 'product_id': 46, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Parede'},
 {'attribute_type_id': 5,
  'id': 165,
  'product_id': 46,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 28, 'id': 166, 'product_id': 46, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 26, 'id': 167, 'product_id': 47, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Fundo'},
 {'attribute_type_id': 5,
  'id': 168,
  'product_id': 47,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 28, 'id': 169, 'product_id': 47, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 26, 'id': 170, 'product_id': 48, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Fundo'},
 {'attribute_type_id': 5,
  'id': 171,
  'product_id': 48,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 28, 'id': 172, 'product_id': 48, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 26, 'id': 173, 'product_id': 49, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Fundo'},
 {'attribute_type_id': 5,
  'id': 174,
  'product_id': 49,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 28, 'id': 175, 'product_id': 49, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 26, 'id': 176, 'product_id': 50, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Fundo'},
 {'attribute_type_id': 5,
  'id': 177,
  'product_id': 50,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 28, 'id': 178, 'product_id': 50, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 5,
  'id': 179,
  'product_id': 51,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 28, 'id': 180, 'product_id': 51, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 5,
  'id': 181,
  'product_id': 52,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 28, 'id': 182, 'product_id': 52, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 5,
  'id': 183,
  'product_id': 53,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Plástico'},
 {'attribute_type_id': 29,
  'id': 184,
  'product_id': 53,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Joelho 90º'},
 {'attribute_type_id': 26,
  'id': 185,
  'product_id': 54,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Passamuros'},
 {'attribute_type_id': 28, 'id': 186, 'product_id': 54, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 26,
  'id': 187,
  'product_id': 55,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Passamuros'},
 {'attribute_type_id': 28, 'id': 188, 'product_id': 55, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 26,
  'id': 189,
  'product_id': 56,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Mecânico'},
 {'attribute_type_id': 30,
  'id': 190,
  'product_id': 56,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Kripsol'},
 {'attribute_type_id': 26,
  'id': 191,
  'product_id': 57,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Mecânico'},
 {'attribute_type_id': 30, 'id': 192, 'product_id': 57, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Wise'},
 {'attribute_type_id': 26,
  'id': 193,
  'product_id': 58,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Standard'},
 {'attribute_type_id': 30,
  'id': 194,
  'product_id': 58,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Astralpool'},
 {'attribute_type_id': 4, 'id': 195, 'product_id': 59, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '290mm'},
 {'attribute_type_id': 26,
  'id': 196,
  'product_id': 59,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Circular'},
 {'attribute_type_id': 28, 'id': 197, 'product_id': 59, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 30,
  'id': 198,
  'product_id': 60,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Kripsol'},
 {'attribute_type_id': 28, 'id': 199, 'product_id': 60, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 5,
  'id': 200,
  'product_id': 61,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 26,
  'id': 201,
  'product_id': 61,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Redondo'},
 {'attribute_type_id': 28, 'id': 202, 'product_id': 61, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Liner'},
 {'attribute_type_id': 4, 'id': 203, 'product_id': 62, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '270mm'},
 {'attribute_type_id': 26,
  'id': 204,
  'product_id': 62,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Circular'},
 {'attribute_type_id': 28, 'id': 205, 'product_id': 62, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 30,
  'id': 206,
  'product_id': 63,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Kripsol'},
 {'attribute_type_id': 28, 'id': 207, 'product_id': 63, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 5,
  'id': 208,
  'product_id': 64,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Aço Inox AISI 316L'},
 {'attribute_type_id': 26,
  'id': 209,
  'product_id': 64,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Redondo'},
 {'attribute_type_id': 28, 'id': 210, 'product_id': 64, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Betão'},
 {'attribute_type_id': 26, 'id': 211, 'product_id': 65, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Branca'},
 {'attribute_type_id': 4, 'id': 212, 'product_id': 65, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '50mm'},
 {'attribute_type_id': 31, 'id': 213, 'product_id': 65, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'LED'},
 {'attribute_type_id': 26, 'id': 214, 'product_id': 66, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Branca'},
 {'attribute_type_id': 4, 'id': 215, 'product_id': 66, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '100mm'},
 {'attribute_type_id': 31, 'id': 216, 'product_id': 66, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'LED'},
 {'attribute_type_id': 26, 'id': 217, 'product_id': 67, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Branca'},
 {'attribute_type_id': 4, 'id': 218, 'product_id': 67, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '170mm'},
 {'attribute_type_id': 31, 'id': 219, 'product_id': 67, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'LED'},
 {'attribute_type_id': 26,
  'id': 220,
  'product_id': 68,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Branco Adaptável'},
 {'attribute_type_id': 4, 'id': 221, 'product_id': 68, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '50mm'},
 {'attribute_type_id': 31, 'id': 222, 'product_id': 68, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'LED'},
 {'attribute_type_id': 26,
  'id': 223,
  'product_id': 69,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Branco Adaptável'},
 {'attribute_type_id': 4, 'id': 224, 'product_id': 69, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '100mm'},
 {'attribute_type_id': 31, 'id': 225, 'product_id': 69, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'LED'},
 {'attribute_type_id': 26,
  'id': 226,
  'product_id': 70,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Branco Adaptável'},
 {'attribute_type_id': 4, 'id': 227, 'product_id': 70, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '170mm'},
 {'attribute_type_id': 31, 'id': 228, 'product_id': 70, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'LED'},
 {'attribute_type_id': 26, 'id': 229, 'product_id': 71, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'RGB'},
 {'attribute_type_id': 4, 'id': 230, 'product_id': 71, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '50mm'},
 {'attribute_type_id': 31, 'id': 231, 'product_id': 71, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'LED'},
 {'attribute_type_id': 26, 'id': 232, 'product_id': 72, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'RGB'},
 {'attribute_type_id': 4, 'id': 233, 'product_id': 72, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '100mm'},
 {'attribute_type_id': 31, 'id': 234, 'product_id': 72, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'LED'},
 {'attribute_type_id': 26, 'id': 235, 'product_id': 73, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'RGB'},
 {'attribute_type_id': 4, 'id': 236, 'product_id': 73, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '170mm'},
 {'attribute_type_id': 31, 'id': 237, 'product_id': 73, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'LED'},
 {'attribute_type_id': 26,
  'id': 238,
  'product_id': 76,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Peristáltica'},
 {'attribute_type_id': 32,
  'id': 239,
  'product_id': 76,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Oxigénio Livre'},
 {'attribute_type_id': 33, 'id': 240, 'product_id': 76, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Eco'},
 {'attribute_type_id': 3, 'id': 241, 'product_id': 77, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '40w'},
 {'attribute_type_id': 1, 'id': 242, 'product_id': 77, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '18m3/h'},
 {'attribute_type_id': 30,
  'id': 243,
  'product_id': 77,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Filtreau'},
 {'attribute_type_id': 33, 'id': 244, 'product_id': 77, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Titan'},
 {'attribute_type_id': 3, 'id': 245, 'product_id': 78, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '80w'},
 {'attribute_type_id': 1, 'id': 246, 'product_id': 78, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '22m3/h'},
 {'attribute_type_id': 30,
  'id': 247,
  'product_id': 78,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Filtreau'},
 {'attribute_type_id': 33, 'id': 248, 'product_id': 78, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Titan'},
 {'attribute_type_id': 3, 'id': 249, 'product_id': 79, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '120w'},
 {'attribute_type_id': 1, 'id': 250, 'product_id': 79, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '28m3/h'},
 {'attribute_type_id': 30,
  'id': 251,
  'product_id': 79,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Filtreau'},
 {'attribute_type_id': 33, 'id': 252, 'product_id': 79, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Titan'},
 {'attribute_type_id': 3, 'id': 253, 'product_id': 80, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '40w'},
 {'attribute_type_id': 1, 'id': 254, 'product_id': 80, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '18m3/h'},
 {'attribute_type_id': 30,
  'id': 255,
  'product_id': 80,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Filtreau'},
 {'attribute_type_id': 33, 'id': 256, 'product_id': 80, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Select'},
 {'attribute_type_id': 3, 'id': 257, 'product_id': 81, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '80w'},
 {'attribute_type_id': 1, 'id': 258, 'product_id': 81, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '22m3/h'},
 {'attribute_type_id': 30,
  'id': 259,
  'product_id': 81,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Filtreau'},
 {'attribute_type_id': 33, 'id': 260, 'product_id': 81, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Select'},
 {'attribute_type_id': 3, 'id': 261, 'product_id': 82, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '100w'},
 {'attribute_type_id': 1, 'id': 262, 'product_id': 82, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '28m3/h'},
 {'attribute_type_id': 30,
  'id': 263,
  'product_id': 82,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Filtreau'},
 {'attribute_type_id': 33, 'id': 264, 'product_id': 82, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Select'},
 {'attribute_type_id': 1, 'id': 265, 'product_id': 83, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '50m3'},
 {'attribute_type_id': 30, 'id': 266, 'product_id': 83, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Aquark'},
 {'attribute_type_id': 33,
  'id': 267,
  'product_id': 83,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Mr. Pure'},
 {'attribute_type_id': 1, 'id': 268, 'product_id': 84, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '90m3'},
 {'attribute_type_id': 30, 'id': 269, 'product_id': 84, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Aquark'},
 {'attribute_type_id': 33,
  'id': 270,
  'product_id': 84,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Mr. Pure'},
 {'attribute_type_id': 1, 'id': 271, 'product_id': 85, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '120m3'},
 {'attribute_type_id': 30, 'id': 272, 'product_id': 85, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Aquark'},
 {'attribute_type_id': 33,
  'id': 273,
  'product_id': 85,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Mr. Pure'},
 {'attribute_type_id': 34, 'id': 274, 'product_id': 86, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '10g/h'},
 {'attribute_type_id': 1, 'id': 275, 'product_id': 86, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '40m3'},
 {'attribute_type_id': 30, 'id': 276, 'product_id': 86, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Aquark'},
 {'attribute_type_id': 33,
  'id': 277,
  'product_id': 86,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Inverclear'},
 {'attribute_type_id': 34, 'id': 278, 'product_id': 87, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '16g/h'},
 {'attribute_type_id': 1, 'id': 279, 'product_id': 87, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '65m3'},
 {'attribute_type_id': 30, 'id': 280, 'product_id': 87, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Aquark'},
 {'attribute_type_id': 33,
  'id': 281,
  'product_id': 87,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Inverclear'},
 {'attribute_type_id': 34, 'id': 282, 'product_id': 88, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '22g/h'},
 {'attribute_type_id': 1, 'id': 283, 'product_id': 88, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '90m3'},
 {'attribute_type_id': 30, 'id': 284, 'product_id': 88, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Aquark'},
 {'attribute_type_id': 33,
  'id': 285,
  'product_id': 88,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Inverclear'},
 {'attribute_type_id': 34, 'id': 286, 'product_id': 89, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '28g/h'},
 {'attribute_type_id': 1, 'id': 287, 'product_id': 89, 'value_boolean': 0, 'value_numeric': 0, 'value_text': '120m3'},
 {'attribute_type_id': 30, 'id': 288, 'product_id': 89, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Aquark'},
 {'attribute_type_id': 33,
  'id': 289,
  'product_id': 89,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Inverclear'},
 {'attribute_type_id': 26,
  'id': 290,
  'product_id': 90,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Upgrade'},
 {'attribute_type_id': 32, 'id': 291, 'product_id': 90, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'PH'},
 {'attribute_type_id': 30, 'id': 292, 'product_id': 90, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Aquark'},
 {'attribute_type_id': 35,
  'id': 293,
  'product_id': 90,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Inverclear'},
 {'attribute_type_id': 26, 'id': 294, 'product_id': 91, 'value_boolean': 0, 'value_numeric': 0, 'value_text': 'Sal'},
 {'attribute_type_id': 18,
  'id': 295,
  'product_id': 91,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Granulado'},
 {'attribute_type_id': 36,
  'id': 296,
  'product_id': 91,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Refinado'},
 {'attribute_type_id': 26,
  'id': 297,
  'product_id': 92,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Anódica'},
 {'attribute_type_id': 32,
  'id': 298,
  'product_id': 92,
  'value_boolean': 0,
  'value_numeric': 0,
  'value_text': 'Proteção Galvânica'},
 {'attribute_type_id': 26,
  'id': 299,
  'product_id': 93,
  'value_boolean': None,
  'value_numeric': None,
  'value_text': 'Doseador Automático'}]


selection_rules = [{'condition_type': 'location',
  'condition_value': 'exterior',
  'id': 1,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 1,
  'rule_name': 'location_exterior'},
 {'condition_type': 'min_capacity',
  'condition_value': '8',
  'id': 2,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 1,
  'rule_name': 'min_capacity_8'},
 {'condition_type': 'location',
  'condition_value': 'exterior',
  'id': 3,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 2,
  'rule_name': 'location_exterior'},
 {'condition_type': 'min_capacity',
  'condition_value': '9',
  'id': 4,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 2,
  'rule_name': 'min_capacity_9'},
 {'condition_type': 'location',
  'condition_value': 'exterior',
  'id': 5,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 3,
  'rule_name': 'location_exterior'},
 {'condition_type': 'min_capacity',
  'condition_value': '14',
  'id': 6,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 3,
  'rule_name': 'min_capacity_14'},
 {'condition_type': 'location',
  'condition_value': 'exterior',
  'id': 7,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 4,
  'rule_name': 'location_exterior'},
 {'condition_type': 'min_capacity',
  'condition_value': '21',
  'id': 8,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 4,
  'rule_name': 'min_capacity_21'},
 {'condition_type': 'location',
  'condition_value': 'exterior',
  'id': 9,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 5,
  'rule_name': 'location_exterior'},
 {'condition_type': 'min_capacity',
  'condition_value': '31',
  'id': 10,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 5,
  'rule_name': 'min_capacity_31'},
 {'condition_type': 'domotics',
  'condition_value': 'false',
  'id': 11,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 6,
  'rule_name': 'domotics_false'},
 {'condition_type': 'domotics',
  'condition_value': 'true',
  'id': 12,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 7,
  'rule_name': 'domotics_true'},
 {'condition_type': 'min_capacity',
  'condition_value': '16',
  'id': 13,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 8,
  'rule_name': 'min_capacity_16'},
 {'condition_type': 'power_type',
  'condition_value': 'monofasica',
  'id': 14,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 8,
  'rule_name': 'power_type_monofasica'},
 {'condition_type': 'pump_type',
  'condition_value': 'variable_speed',
  'id': 15,
  'is_active': 1,
  'operator': '=',
  'priority': 10,
  'product_id': 8,
  'rule_name': 'pump_type_variable_speed'},
 {'condition_type': 'min_capacity',
  'condition_value': '20',
  'id': 16,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 9,
  'rule_name': 'min_capacity_20'},
 {'condition_type': 'power_type',
  'condition_value': 'monofasica',
  'id': 17,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 9,
  'rule_name': 'power_type_monofasica'},
 {'condition_type': 'pump_type',
  'condition_value': 'variable_speed',
  'id': 18,
  'is_active': 1,
  'operator': '=',
  'priority': 10,
  'product_id': 9,
  'rule_name': 'pump_type_variable_speed'},
 {'condition_type': 'min_capacity',
  'condition_value': '25',
  'id': 19,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 10,
  'rule_name': 'min_capacity_25'},
 {'condition_type': 'power_type',
  'condition_value': 'monofasica',
  'id': 20,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 10,
  'rule_name': 'power_type_monofasica'},
 {'condition_type': 'pump_type',
  'condition_value': 'variable_speed',
  'id': 21,
  'is_active': 1,
  'operator': '=',
  'priority': 10,
  'product_id': 10,
  'rule_name': 'pump_type_variable_speed'},
 {'condition_type': 'min_capacity',
  'condition_value': '7.5',
  'id': 22,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 11,
  'rule_name': 'min_capacity_7.5'},
 {'condition_type': 'power_type',
  'condition_value': 'monofasica',
  'id': 23,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 11,
  'rule_name': 'power_type_monofasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '11',
  'id': 24,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 12,
  'rule_name': 'min_capacity_11'},
 {'condition_type': 'power_type',
  'condition_value': 'monofasica',
  'id': 25,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 12,
  'rule_name': 'power_type_monofasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '16',
  'id': 26,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 13,
  'rule_name': 'min_capacity_16'},
 {'condition_type': 'power_type',
  'condition_value': 'monofasica',
  'id': 27,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 13,
  'rule_name': 'power_type_monofasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '21.5',
  'id': 28,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 14,
  'rule_name': 'min_capacity_21.5'},
 {'condition_type': 'power_type',
  'condition_value': 'monofasica',
  'id': 29,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 14,
  'rule_name': 'power_type_monofasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '26',
  'id': 30,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 15,
  'rule_name': 'min_capacity_26'},
 {'condition_type': 'power_type',
  'condition_value': 'monofasica',
  'id': 31,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 15,
  'rule_name': 'power_type_monofasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '35',
  'id': 32,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 16,
  'rule_name': 'min_capacity_35'},
 {'condition_type': 'power_type',
  'condition_value': 'monofasica',
  'id': 33,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 16,
  'rule_name': 'power_type_monofasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '7.5',
  'id': 34,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 17,
  'rule_name': 'min_capacity_7.5'},
 {'condition_type': 'power_type',
  'condition_value': 'trifasica',
  'id': 35,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 17,
  'rule_name': 'power_type_trifasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '11',
  'id': 36,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 18,
  'rule_name': 'min_capacity_11'},
 {'condition_type': 'power_type',
  'condition_value': 'trifasica',
  'id': 37,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 18,
  'rule_name': 'power_type_trifasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '16',
  'id': 38,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 19,
  'rule_name': 'min_capacity_16'},
 {'condition_type': 'power_type',
  'condition_value': 'trifasica',
  'id': 39,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 19,
  'rule_name': 'power_type_trifasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '21.5',
  'id': 40,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 20,
  'rule_name': 'min_capacity_21.5'},
 {'condition_type': 'power_type',
  'condition_value': 'trifasica',
  'id': 41,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 20,
  'rule_name': 'power_type_trifasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '26',
  'id': 42,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 21,
  'rule_name': 'min_capacity_26'},
 {'condition_type': 'power_type',
  'condition_value': 'trifasica',
  'id': 43,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 21,
  'rule_name': 'power_type_trifasica'},
 {'condition_type': 'min_capacity',
  'condition_value': '35',
  'id': 44,
  'is_active': 1,
  'operator': '>=',
  'priority': 0,
  'product_id': 22,
  'rule_name': 'min_capacity_35'},
 {'condition_type': 'power_type',
  'condition_value': 'trifasica',
  'id': 45,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 22,
  'rule_name': 'power_type_trifasica'},
 {'condition_type': 'domotics',
  'condition_value': 'false',
  'id': 46,
  'is_active': 1,
  'operator': '=',
  'priority': 1,
  'product_id': 25,
  'rule_name': 'domotics_false'},
 {'condition_type': 'domotics',
  'condition_value': 'false',
  'id': 47,
  'is_active': 1,
  'operator': '=',
  'priority': 1,
  'product_id': 26,
  'rule_name': 'domotics_false'},
 {'condition_type': 'domotics',
  'condition_value': 'false',
  'id': 48,
  'is_active': 1,
  'operator': '=',
  'priority': 1,
  'product_id': 27,
  'rule_name': 'domotics_false'},
 {'condition_type': 'max_power',
  'condition_value': '50',
  'id': 49,
  'is_active': 1,
  'operator': '<=',
  'priority': 0,
  'product_id': 28,
  'rule_name': 'max_power_50'},
 {'condition_type': 'domotics',
  'condition_value': 'true',
  'id': 50,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 28,
  'rule_name': 'domotics_true'},
 {'condition_type': 'max_power',
  'condition_value': '100',
  'id': 51,
  'is_active': 1,
  'operator': '<=',
  'priority': 0,
  'product_id': 29,
  'rule_name': 'max_power_100'},
 {'condition_type': 'domotics',
  'condition_value': 'true',
  'id': 52,
  'is_active': 1,
  'operator': '=',
  'priority': 0,
  'product_id': 29,
  'rule_name': 'domotics_true'},
 {'condition_type': 'max_power',
  'condition_value': '50',
  'id': 53,
  'is_active': 1,
  'operator': '<=',
  'priority': 0,
  'product_id': 30,
  'rule_name': 'max_power_50'},
 {'condition_type': 'domotics',
  'condition_value': 'true',
  'id': 54,
  'is_active': 1,
  'operator': '=',
  'priority': 5,
  'product_id': 30,
  'rule_name': 'domotics_true'},
 {'condition_type': 'max_power',
  'condition_value': '100',
  'id': 55,
  'is_active': 1,
  'operator': '<=',
  'priority': 0,
  'product_id': 31,
  'rule_name': 'max_power_100'},
 {'condition_type': 'domotics',
  'condition_value': 'true',
  'id': 56,
  'is_active': 1,
  'operator': '=',
  'priority': 5,
  'product_id': 31,
  'rule_name': 'domotics_true'},
 {'condition_type': 'location',
  'condition_value': 'interior',
  'id': 57,
  'is_active': 1,
  'operator': '=',
  'priority': 10,
  'product_id': 32,
  'rule_name': 'location_interior'}]


product_alternatives = []


price_multipliers = [{'applies_to': 'all',
  'condition_type': 'access_level',
  'condition_value': 'facil',
  'id': 1,
  'is_active': 1,
  'multiplier': 1,
  'name': 'Acesso Fácil',
  'target_id': None},
 {'applies_to': 'all',
  'condition_type': 'access_level',
  'condition_value': 'medio',
  'id': 2,
  'is_active': 1,
  'multiplier': 1.15,
  'name': 'Acesso Médio',
  'target_id': None},
 {'applies_to': 'all',
  'condition_type': 'access_level',
  'condition_value': 'dificil',
  'id': 3,
  'is_active': 1,
  'multiplier': 1.3,
  'name': 'Acesso Difícil',
  'target_id': None},
 {'applies_to': 'all',
  'condition_type': 'excavation',
  'condition_value': 'false',
  'id': 4,
  'is_active': 1,
  'multiplier': 1,
  'name': 'Sem Escavação',
  'target_id': None},
 {'applies_to': 'all',
  'condition_type': 'excavation',
  'condition_value': 'true',
  'id': 5,
  'is_active': 1,
  'multiplier': 1.2,
  'name': 'Com Escavação',
  'target_id': None},
 {'applies_to': 'all',
  'condition_type': 'shape',
  'condition_value': 'standard',
  'id': 6,
  'is_active': 1,
  'multiplier': 1,
  'name': 'Forma Standard',
  'target_id': None},
 {'applies_to': 'all',
  'condition_type': 'shape',
  'condition_value': 'especial',
  'id': 7,
  'is_active': 1,
  'multiplier': 1.25,
  'name': 'Forma Especial',
  'target_id': None},
 {'applies_to': 'all',
  'condition_type': 'domotics',
  'condition_value': 'false',
  'id': 8,
  'is_active': 1,
  'multiplier': 1,
  'name': 'Sem Domótica',
  'target_id': None},
 {'applies_to': 'all',
  'condition_type': 'domotics',
  'condition_value': 'true',
  'id': 9,
  'is_active': 1,
  'multiplier': 1.1,
  'name': 'Com Domótica',
  'target_id': None}]


special_prices = []

